{
    "0_1": "Beckon Sign \"Danmaku Business Boom\"",
    "1_1": "Money Sign \"Casting Koban Coins Before a Calico Cat\"",
    "2_1": "Autumn Sign \"Bumper Crop Waves\"",
    "3_1": "Butterfly Sign \"Deadly Butterfly\"",
    "4_1": "Kitchen Knife \"Mince Up Till Your Blade Chips\"",
    "5_1": "\"Perfect Freeeeeeeeze!\"",
    "6_1": "Song Sign \"Mermaid's Song\"",
    "7_1": "\"Life of a Nimble Severed Head\"",
    "8_1": "\"Ripples of Rapacity\"",
    "9_1": "Stone Sign \"Red Stone Stack of Aja\"",
    "10_1": "\"Watershed of Life\"",
    "11_1": "\"5.67 Billion Years of Menial Labour\"",
    "12_1": "\"Money and Death Busily Piling Up.\"",
    "13_1": "Miracle \"Miracle Pentacle\"",
    "14_1": "Time Sign \"Eye-wink Knife Hell\"",
    "15_1": "Swordmanship \"Mouryou Wiping Blood From Their Blades\"",
    "16_1": "\"Full House Amulets: Bullet Money Bonus Packets\"",
    "17_1": "Fox Sign \"Delayed Pipe Fox Bullet\"",
    "17_2": "Fox Sign \"Wickedness Within the Pipe\"",
    "18_1": "Star Sign \"Star of Ingenuous Brilliance\"",
    "18_2": "Wind Sign \"Wind of Lonesome Emptiness\"",
    "19_1": "Great Blaze \"The Very, Very Bottom of Hell's Cauldron\"",
    "19_2": "\"Lunatic Torch Relay\"",
    "20_1": "Keystone \"Qian & Kun Rumbling Cannon\"",
    "20_2": "Keystone \"Diffuse Qian & Kun Rumbling Cannon\"",
    "21_1": "Dense Sign \"Ongyouki of Density\"",
    "21_2": "\"Chief General of the Will-o'-wisps\"",
    "22_1": "\"First and Last of Its Kind: Black Market with a Giant Queue\"",
    "22_2": "Danmaku Transformation \"Youkai Biocenosis\"",
    "23_1": "Heavenly Stellar Steed \"Pegasus Cross\"",
    "23_2": "\"This Explosion is Muscle Strength!\"",
    "24_1": "Kodoku \"Revolt Swarmer\"",
    "24_2": "\"Grudge of Torn-Apart Insects Writhing in Agony\"",
    "25_1": "\"Legitimate Bullet Market\"",
    "25_2": "\"Black Market Michigan Roll\"",
    "26_1": "Weapon \"Water Flamethrower\"",
    "26_2": "\"Like the Flow of the Mountain Marsh\"",
    "27_1": "Monochrome Dream \"Coal Dream of the Naughty Ones\"",
    "27_2": "Christmas Dream \"Present Wrapping Dream\"",
    "27_3": "\"Kyuoka Danmaku Fireworks\""
}